### ISSUE TITLE
Crate does not compile with Rust rustc 1.36.0-nightly (597f43248 2019-04-26)

### ISSUE THREAD

**Issue by matobet** [tinaun/gen-iter#2]
Upon including a dependency upon `gen-iter 0.1.2`, the project fails to compile with:
```
   Compiling gen-iter v0.1.2
error[E0599]: no method named `resume` found for type `T` in the current scope
  --> /home/matobet/.cargo/registry/src/github.com-1ecc6299db9ec823/gen-iter-0.1.2/src/lib.rs:53:22
   |
53 |         match self.0.resume() {
   |                      ^^^^^^
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `resume`, perhaps you need to implement it:
           candidate #1: `std::ops::Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `gen-iter`.

To learn more, run the command again with --verbose.
```

**Comment by Seeker14491** [comment]
A working fork is available: https://github.com/sumeet/gen-iter
